version: "3.7"

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres-test'
      - 'POSTGRES_PASSWORD=@1234!Nakybono'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5436:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      exercise-network:

  app:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile

    restart: on-failure

    ports:
      - '8088:8080'

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres-test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=@1234!Nakybono

    networks:
      exercise-network:

volumes:
  postgres_data:

networks:
  exercise-network:
    driver: bridge